### PR TITLE
Add ability to set output without `<script>` tag

### PR DESCRIPTION
**Pull request by muhammadcahya**
For best practice the script must be loaded before tag body, so all javascript for web user interface is fully loaded first and then load google analytic js, I pull request this changes to handle this. So for old configuration still same and not change with my commit.

What your opinion ?

### CODE REVIEW

**Comment by antonkomarev** [comment]
Thank you for the support!

Here is a nice [post about GA script position in HTML on StackOverflow](http://stackoverflow.com/questions/5370490/should-google-analytics-go-in-the-head-or-bottom-of-an-html-page/5370525#5370525).

But it is a good idea to give user a choice how to load the script. The only thing I'm not sure with in your PR - parameter name. I'd prefer more obvious name like:

``` php
public $omitScriptTag = false;
```

And it will be `false` in that case by default.

If you will change the name I will be glad to merge it.

**Comment by muhammadcahya** [comment]
It is a pull request related to the previous discussion, if there is anything else please tell me again :)

**Comment by antonkomarev** [comment]
@muhammadcahya Thank you. Merged and updated a bit README.md and code style.

**Comment by muhammadcahya** [comment]
Sorry, there was a bit strange in readme **Example of advanced usage**
If the config `omitScriptTag` set by `true`, and then use with `GATracking::widget`  "only", will not generated `<script>` tag ? 
I think for this configuration in this example, `omitScriptTag` must set `false` to generate `<script>` tag If in this example wants to bring the full configuration params

Is there anything wrong here, or you have other considerations?

**Comment by antonkomarev** [comment]
@muhammadcahya You are right. Will fix it.

**Pull request merged**
